### ISSUE TITLE
add support for on/off/sleep/restart to schedule json

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#105]
to allow scheduled down-time.

**Comment by wvengen** [comment]
Allowing to specify an on/off schedule in the admin interface would be another option.

**Comment by mobione** [comment]
on/off/sleep/restart in json.... That would be so great... it will however not be possible to use 'Chrome Sign Build' for making schedules that works directly with KIOSK... but I can live with that. 

It would also be nice if you implement: "defaultUrl": "http://someurl.com" from 'Chrome Sign Build' JSON so that we can show default "pause" content.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/add-support-for-on-off-sleep-restart-to-schedule-json/128
