### ISSUE TITLE
Cursor shown over content

### ISSUE THREAD

**Issue by ozob3999** [matt-cook/kiosk#114]
I have the display and Chromebit set on a timer.  When they first come on in the morning, the cursor shows up and won't go away, even after several hours.  If I disconnect power for a few moments and re-connect, the cursor is gone.  I have two different kiosks set up, and they both do the same thing.  Any thoughts?

**Comment by matt-cook** [comment]
Do you have the `Hide Cursor` selected on the setup page? This should be enabled to hide the cursor.

**Comment by ozob3999** [comment]
Yes; that works fine,  I have selected 'Hide Cursor'.  But when it turns back on after being completely off, the cursor shows back up again.  It seems like a bug in the system.

**Comment by matteoraggi** [comment]
I have a similar problem with raspbian 8 and chromium 51 (hardware is raspberry pi 3 model B) . 
I selected  Hide Cursor on the setup page, but the mouse disappear only when I move it, but I need that the mouse disappear by itself and without my mouse movement, because my kiosks will be without mouse. PRobably the same issue is with windows 10, if you want I can do this test too.

**Comment by blixloop24** [comment]
I have exact same problem, running on Raspbian and chromium (Rasberry PI3)
When i do the same with Windows 10 on an Intel Compute Stick it does not show the mouse cursor.
Any solution to this?

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/cursor-shown-over-content/106
