### ISSUE TITLE
Clear cache after inactivity reset

### ISSUE THREAD

**Issue by slampaq** [matt-cook/kiosk#142]
Hi Matt,

Is it possible to do a clear cache when doing an inactivity reset?

When we edit the settings in the Kiosk app and enable "clear cache on save", the requested URL with new data is loaded perfectly. However this data can chance every hour in our situation. We therefore enable the inactivity reset after 60 minutes, however in that case the cache is not cleared. Moreover, even when we enable daily restart, the old data is still cached and not updated. Do you have any advice on how to do this?

Keep up the good work!

Regards,

Koen

**Comment by welrachid** [comment]
Perhaps there should be a setting that forces cache clearing on each reset/restart

**Comment by thegreatmongoose** [comment]
Hello Matt,
I'd like to second this request. I am a teacher and I use Kiosk to keep students where they should be on test day (and to prevent screen shots etc...). I'm hoping to expand my use of kiosk to more than just tests but the problem is that if a student logs into their google account (we are a google school) in Kiosk mode it stays logged in. So if they shut down the computer the next student can log on and get to their information. It would be nice if their login information was reset with each restart.
Thank you for an already amazing tool!
-Alex
