### ISSUE TITLE
Clearing Cache

### ISSUE THREAD

**Issue by thegreatmongoose** [matt-cook/kiosk#181]
Hello and thank you for this wonderful app.
I am a high school teacher and I use the kiosk app to securely administer tests. One of the issues I run into is that when students close the kiosk app the cache doesn't clear so if they forget  to log out (which they always do) then the next student has access to their accounts. Is it possible to add an option to clear the cache when the kiosk app closes (or opens for that matter). 

Thank you again,
Alex

PS I typed this up earlier but didn't see it posted so I think i may have forgotten to submit it so if this is a repeat request I'm very sorry

**Comment by dcarlton-bhbl** [comment]
I am also having this problem with Google Forms. The students can sign another student out, but it shows all of the cache student accounts from previous users. Furthermore, when a new student logs in on the pop-window that Google Forms sends the user to, a Google Docs page launch in that window instead of the pop-up closing and taking the user back to the Form.

**Comment by RabsRincon** [comment]
Ey! I opened a Pull Request that might fix inderectly your problems. It adds a an option on the admin page to toggle the cache/cookies etc removal on restart/reload.

I think it's what you are looking for. The PR in question is #185 so you can keep track of when/if it gets merged

**Comment by xinthose** [comment]
This is how to do it from a Linux terminal
```
killall -w -r chrome     # kiosk app must be closed before clearing the cache
rm -r /home/xinthose/.config/google-chrome/Default/Storage/ext/afhcomalholahplbjhnmahkoekoijban/*
```
