### ISSUE TITLE
Asus Chromebook is on Kiosk mode but can't get out of it

### ISSUE THREAD

**Issue by binnybinanth** [matt-cook/kiosk#187]
Asus Chromebook is on Kiosk mode but can't get out of it, I tried all the shortcut keys , I want to get back to the login screen

And also I want this to be always on, never on sleep , I am using prevent from sleeping option but when i close the laptop and re-open it , it fails to connect to wifi 

Please help

**Comment by backslashgithub** [comment]
ctrl-a ?

**Comment by binnybinanth** [comment]
I accidentally disabled local admin and I am not able to power restart the chrome book at all, so at this moment I am stuck , not sure how I can turn on the local administration and from there how I can restart , please help

**Comment by Ken-L** [comment]
You'll have to physically power cycle the chrome box (press and hold the power button?) otherwise run that bad boy till it dies then power it back up, while the box is launching the application ctrl+alt+s. You should now be at the login screen. Login and open the chrome browser. In the URL field enter chrome://extensions and find the Kiosk app. Delete it. Restart the chrome box for good measure. Once rebooted login and re-add the kiosk application to chrome and enable auto launch. From there you enter the setup. That's all I've got.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/asus-chromebook-is-on-kiosk-mode-but-cant-get-out-of-it/100

**Comment by erikasalcedo** [comment]
@Ken-L I am having the same issue. When I delete the app and reboot the computer it still auto launches kiosk even though it's been deleted. Have you encountered this issue before?

**Comment by techmaurice** [comment]
> This issue was moved to https://discuss.kiosk.cook.company/t/asus-chromebook-is-on-kiosk-mode-but-cant-get-out-of-it/100

This URL is broken, unfortunately, and I need this info.
