### ISSUE TITLE
Keyboard Shortcuts and Hotkeys bypass Kiosk

### ISSUE THREAD

**Issue by Jamman** [matt-cook/kiosk#209]
I'm finding ways to exit the kiosk for a user - which defeats the purpose.
ESC, F4, F5 all allow it to exit it.  Using the Start/Win key brings up the menu - doesnt seem to allow opening stuff though.

Are there options to disable these?  If so, where?

**Comment by matt-cook** [comment]
This functionality has been a moving target. It's been tough to keep it locked down on OSX/Windows. More details in https://github.com/matt-cook/kiosk/pull/208 and https://github.com/matt-cook/kiosk/issues/4.

Google has announced they won't be supporting Chrome apps on OSX/Windows starting in 2018. So further efforts for those platforms are going into a separate version of the app. This bug won't be fixed in the Chrome app version.

**Comment by Jamman** [comment]
Is there a non-Chrome App version?

**Comment by matt-cook** [comment]
Not yet. It's in progress.
