### ISSUE TITLE
mp4 video files do not get cached, even with cache-control header

### ISSUE THREAD

**Issue by coryrobinson** [matt-cook/kiosk#219]
We are using the kiosk app for displaying mp4 videos using the html5 video tag.  However, the mp4 files are being downloaded from the server (in several 206 partial content chunks/streams) each time.  We are setting the cache-control header to max-age=86400, but that seems to be ignored.  The mp4s are cached as expected if using Chrome outside of the kiosk app.  We are doing this on an Asus Chromebook.

**Comment by ericholmer** [comment]
This doesn't directly fix your issue, but would you be able to test if you are encountering the same issue if the videos are encoded using webm? I recall having an issue with MP4 & Kiosk in the past but WEBM seemed to work fine.

**Comment by akeilox** [comment]
im having the same issue. @ericholmer are you saying .webm solves the cachine issue observerd with .mp4 ?

**Comment by michaelvelasquez** [comment]
We're also having the same issue with mp4 videos that are meant to loop. Rather than download the entire video(s) once and play from cache, Chrome just keeps downloading partial 206 chunks over and over again and it's killing our bandwidth. But we also have the issue in Chrome outside the kiosk app. I'm curious, are you doing anything special to get Chrome to cache your videos? Based on some cursory research, I was led to believe that this was a function of Chrome? https://stackoverflow.com/questions/18251632/another-force-chrome-to-fully-buffer-mp4-video
Safari, for example, works as expected by downloading once and playing from cache.

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/mp4-video-files-do-not-get-cached-even-with-cache-control-header/78
