### ISSUE TITLE
ability to rotate URLs

### ISSUE THREAD

**Issue by jakeyr** [matt-cook/kiosk#24]
It would be great to have Kiosk be able to cycle through a few URLs instead of just one. Configurable features could include:
- Time spent on each page.
- Whether to refresh each page or not, and how regularly.

Currently you can do this with iframes and javascript, but it would be nice to simplify!

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=10818921)](https://www.bountysource.com/issues/10818921-ability-to-rotate-urls?utm_source=10818921&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by jonoscott** [comment]
Very keen to see this one,  perhaps using the | or a space or comma between URL's?

**Comment by davidcmoody** [comment]
Yes, I would love to see this feature also.  Currently, I've had to modify my meta tag with a PHP script to rotate the pages automatically.  Would be nice if this was built in.

**Comment by matt-cook** [comment]
Thanks for the requests. This isn't currently on our development schedule, since we haven't needed it. 

The current workaround would be setting up wrapper or redirect like @davidcmoody describes or possibly using the schedule server feature. 

It's a great idea, so if you'd like to dedicate resources please feel free to submit a pull request or add a bounty here: https://www.bountysource.com/issues/10818921-ability-to-rotate-urls

**Comment by nmarshallnz** [comment]
Yep
Would also like to see this feature. This would complete our Kiosk rollout in in Auckland. 
What kind of Bounty are we looking at to get it developed?

**Comment by Ombridride** [comment]
First, thank you for your work on this kiosk application !

I would also like this addition on your Kiosk app :)

**Comment by xd1936** [comment]
Don't forget, you can **ctrl + shift + f3** on ChromeOS to rotate. I know this isn't the same, but it works for us right now on our vertical TVs.

**Comment by matt-cook** [comment]
This functionality has been added in v5.10.0.
