### ISSUE TITLE
Refresh data after slides loop

### ISSUE THREAD

**Issue by pjamies** [matt-cook/kiosk#240]
Hello,

Is there a way (in the future) to add the ability to refresh the data after a Google Slides
show loops (starts again). We sometimes change a Google Slides show (add-update) a
presentation, but the only time it updates the slide show is during a timeout or preset
time. This way any changes will not have to wait.
Next question: how does the remote access work? I have tried to remote into the Chrome Device
but cannot seem to get both devices connected.

**Comment by ScoopDL** [comment]
I am using this in the same way and have a question for you - how are you running this? Do you have the device in kiosk mode so that it auto loads into the slideshow when the device powers on? 

Entering the URL in kiosk mode at startup is a pain since I can't load anything but the kiosk app and cannot cut and paste the generated slideshow url. I tried that and I get an error from google docs (I thought since it's not logged into a google account, but it works on a windows PC when I'm not logged into a google account?). I cannot log into a google account when auto-loading this app at startup since it's the only thing that runs.

And every 48 hours the device shuts down for some reason - this is supposed to be fixed in an update on August 1st, but wouldn't be an issue if I could get the slideshow to autoload at startup.

Please let me know your setup so I can copy :-)

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/refresh-data-after-slides-loop/60
