### ISSUE TITLE
Kiosk App Crashes on Chrome Box

### ISSUE THREAD

**Issue by Oscar-the-Ghost** [matt-cook/kiosk#247]
We're using the Kiosk app to limit the webpage access of two public terminals (both Chrome desktops), but the app keeps crashing, nullifying its purpose.  It will function fine for hours and then just crash for no reason.  We don't know why it crashes - there's no trigger, as far as we can tell, and it happens even overnight when no one is using the computers - but we get the notification bubble that it's crashed.  Since we're not watching it all the time - that's kind of the point - sometimes we don't notice immediately.  It seems to happen on both computers.  How can we fix this problem?

**Comment by kardoud44** [comment]
Do you use the daily restart et inactivity reset?
I am having a similar problem with the app @Oscar-the-Ghost

**Comment by ScoopDL** [comment]
Mine does this pretty much exactly every 48 hours like clockwork. At first, I noticed a "storage full" warning and realized that it was necessary to clear cache upon refreshing the webpage using the option in the kiosk app settings. There was no way to clear the used data in the Chrome  OS settings.

I'm not sure if it has to do with the fact that I cannot use developer options to place the OS itself into kiosk mode since I bought a consumer "off-the-shelf" chromebox (it's not "managed"). If I could get this mode to work then I could use kardoud44's suggestion and use a daily restart and have the app auto load at startup. But this isn't an option for me.

I love the app but wish I didn't have to go to my kiosks every two days and restart the app.

**Comment by matt-cook** [comment]
Thanks for the note guys. I'm aware of this issue and the latest version (v5.12.0: https://github.com/matt-cook/kiosk/pull/251 scheduled for release Aug. 1) should have a fix for this issue. Please do let me know if it continues to be a problem.
