### ISSUE TITLE
add handling for onSuspend and onRestartRequired events

### ISSUE THREAD

**Issue by matt-cook** [matt-cook/kiosk#47]
https://developer.chrome.com/extensions/runtime#event-onRestartRequired

**Comment by matt-cook** [comment]
Does not apply since this is an app versus an extension? https://developer.chrome.com/apps/app_runtime

Or does it? https://developer.chrome.com/apps/app_lifecycle

**Comment by kzahel** [comment]
Yes, I believe it applies. The rationale is usually when there's a long-due chrome system update, or perhaps the management console triggers a restart?

**Comment by kzahel** [comment]
https://developer.chrome.com/extensions/runtime#event-onRestartRequired
"onRestartRequired

Since Chrome 29.

Fired when an app or the device that it runs on needs to be restarted. The app should close all its windows at its earliest convenient time to let the restart to happen. If the app does nothing, a restart will be enforced after a 24-hour grace period has passed. Currently, this event is only fired for Chrome OS kiosk apps."

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/add-handling-for-onsuspend-and-onrestartrequired-events/147
