### ISSUE TITLE
add option to serve remote admin page on all network interfaces

### ISSUE THREAD

**Issue by heaversm** [matt-cook/kiosk#63]
I have a site whose URL varies depending on my current IP address (using local server MAMP with XIP feature) - because of this, the URL I put into Kiosk's config screen is no longer valid. Now I can't access the administration screen to change the URL, because when I launch the site there's just a `web page is not available` -`ERROR_CONNECTION_TIMED_OUT` message. 

Is there a way to do this?

If not, I would recommend a feature which detects a lack of connection, and sends the user to the admin screen.

**Comment by matt-cook** [comment]
I assume this is for remote administration?

You should be able to use `ctrl+a` to bring up the local admin page regardless of content load status, or is this a problem you're having as well?

**Comment by heaversm** [comment]
Ah - sorry - this is a tablet, so there is no peripheral keyboard

**Comment by matt-cook** [comment]
Thanks for the detail, I think the solution will be adding an option (probably default) to serve on all adapters instead of specifically selecting. 

Unfortunately, in the short-term I don't think we have a workaround on the app side of things. I'm renaming the issue so we can address it in a future version. If it's a major blocking issue for you, let us know.

**Comment by heaversm** [comment]
Not a major blocker - just involves uninstalling and reinstalling the app to change the address - luckily you've made that bit easy. Thanks for considering a fix. Let me know if you update it.

**Comment by martbhell** [comment]
When our Asus Chromebox starts in kiosk mode with this app it first says "There is no internet connection" for a few seconds and then the chosen web page is displayed. Until I go into the CTRL+A and press save the remote management interface is unreachable (port says filtered, not closed so seems it's not up at all). 
Perhaps this error could be fixed by listening on all interfaces (assuming that the app starts before network is really up and then it can't listen on the previously selected interface)

**Comment by matt-cook** [comment]
This issue was moved to https://discuss.kiosk.cook.company/t/add-option-to-serve-remote-admin-page-on-all-network-interfaces/145
